export type Activity = {
  id: string;
  userId: string;
  resourceState: number;
  athleteId?: number;
  athleteResourceState?: number;
  name: string;
  distance: number;
  movingTime: number;
  elapsedTime: number;
  totalElevationGain: number;
  type: string;
  sportType: string;
  workoutType?: number | null;
  startDate: string; // ISO string or Date
  startDateLocal: string; // ISO string or Date
  timezone?: string;
  utcOffset?: number;
  locationCity?: string;
  locationState?: string;
  locationCountry?: string;
  achievementCount: number;
  kudosCount: number;
  commentCount: number;
  athleteCount: number;
  photoCount: number;
  mapId?: string;
  summaryPolyline?: string;
  mapResourceState?: number;
  trainer: boolean;
  commute: boolean;
  manual: boolean;
  private: boolean;
  visibility?: string;
  flagged: boolean;
  gearId?: string;
  startLat?: number;
  startLng?: number;
  endLat?: number;
  endLng?: number;
  averageSpeed?: number;
  maxSpeed?: number;
  hasHeartrate: boolean;
  averageHeartrate?: number | null;
  maxHeartrate?: number | null;
  heartrateOptOut: boolean;
  displayHideHeartrateOption: boolean;
  elevHigh?: number;
  elevLow?: number;
  uploadId?: string | number | null;
  uploadIdStr?: string;
  externalId?: string;
  fromAcceptedTag: boolean;
  prCount: number;
  totalPhotoCount: number;
  hasKudoed: boolean;
  createdAt?: string;
  updatedAt?: string;
  map?: {
    id?: string;
    summary_polyline?: string;
  };
};
